[package]
name = "fon"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

license = "MIT OR Apache-2.0 OR Zlib"
documentation = "https://docs.rs/fon"
homepage = "https://github.com/AldaronLau/fon/blob/master/CHANGELOG.md"
repository = "https://github.com/AldaronLau/fon"
readme = "README.md"
description = "Rust audio types, resampling and mixing library."
keywords = ["audio", "conversion", "processing", "wave", "sound"]
categories = ["multimedia::audio", "multimedia"]

[dependencies]
